# Generated by Django 5.2.6 on 2025-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
