# Generated by Django 5.2.6 on 2025-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('socks', 'Socks'), ('accessories', 'Accessories')], default='update', max_length=20),
        ),
    ]
