# Generated by Django 5.2.6 on 2025-09-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
