# Generated by Django 5.2.6 on 2025-09-23 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('ball', 'Ball'), ('socks', 'Socks'), ('accessories', 'Accessories')], default='jersey', max_length=20),
        ),
    ]
